// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/config-service/proto/validate/validate.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_config_validate is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/config-service/proto/validate/validate.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_config_validate

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Id               []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type Response struct {
	IsValid          *bool    `protobuf:"varint,1,req,name=isValid" json:"isValid,omitempty"`
	PresentSchema    []string `protobuf:"bytes,2,rep,name=presentSchema" json:"presentSchema,omitempty"`
	AbsentSchema     []string `protobuf:"bytes,3,rep,name=absentSchema" json:"absentSchema,omitempty"`
	Error            []string `protobuf:"bytes,4,rep,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetIsValid() bool {
	if m != nil && m.IsValid != nil {
		return *m.IsValid
	}
	return false
}

func (m *Response) GetPresentSchema() []string {
	if m != nil {
		return m.PresentSchema
	}
	return nil
}

func (m *Response) GetAbsentSchema() []string {
	if m != nil {
		return m.AbsentSchema
	}
	return nil
}

func (m *Response) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
}
