// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/config-service/proto/diff/diff.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_config_diff is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/config-service/proto/diff/diff.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_config_diff

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Path             *string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Config           *string `protobuf:"bytes,3,req,name=config" json:"config,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Request) GetConfig() string {
	if m != nil && m.Config != nil {
		return *m.Config
	}
	return ""
}

type Response struct {
	Diff             *string `protobuf:"bytes,1,opt,name=diff" json:"diff,omitempty"`
	Patch            *string `protobuf:"bytes,2,opt,name=patch" json:"patch,omitempty"`
	ExistingConfig   *string `protobuf:"bytes,3,opt,name=existingConfig" json:"existingConfig,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetDiff() string {
	if m != nil && m.Diff != nil {
		return *m.Diff
	}
	return ""
}

func (m *Response) GetPatch() string {
	if m != nil && m.Patch != nil {
		return *m.Patch
	}
	return ""
}

func (m *Response) GetExistingConfig() string {
	if m != nil && m.ExistingConfig != nil {
		return *m.ExistingConfig
	}
	return ""
}

func init() {
}
