// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/config-service/proto/common.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_config is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/config-service/proto/common.proto

It has these top-level messages:
	ChangeMeta
	Change
*/
package com_HailoOSS_service_config

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ChangeMeta struct {
	ChangeId         *string `protobuf:"bytes,5,req,name=changeId" json:"changeId,omitempty"`
	Timestamp        *int64  `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	AuthMechanism    *string `protobuf:"bytes,2,req,name=authMechanism" json:"authMechanism,omitempty"`
	UserId           *string `protobuf:"bytes,3,req,name=userId" json:"userId,omitempty"`
	Message          *string `protobuf:"bytes,4,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChangeMeta) Reset()         { *m = ChangeMeta{} }
func (m *ChangeMeta) String() string { return proto.CompactTextString(m) }
func (*ChangeMeta) ProtoMessage()    {}

func (m *ChangeMeta) GetChangeId() string {
	if m != nil && m.ChangeId != nil {
		return *m.ChangeId
	}
	return ""
}

func (m *ChangeMeta) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ChangeMeta) GetAuthMechanism() string {
	if m != nil && m.AuthMechanism != nil {
		return *m.AuthMechanism
	}
	return ""
}

func (m *ChangeMeta) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *ChangeMeta) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type Change struct {
	ChangeId         *string `protobuf:"bytes,1,req,name=changeId" json:"changeId,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	AuthMechanism    *string `protobuf:"bytes,4,req,name=authMechanism" json:"authMechanism,omitempty"`
	UserId           *string `protobuf:"bytes,5,req,name=userId" json:"userId,omitempty"`
	Message          *string `protobuf:"bytes,6,req,name=message" json:"message,omitempty"`
	Config           *string `protobuf:"bytes,7,req,name=config" json:"config,omitempty"`
	Path             *string `protobuf:"bytes,8,opt,name=path" json:"path,omitempty"`
	OldConfig        *string `protobuf:"bytes,9,opt,name=oldConfig" json:"oldConfig,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}

func (m *Change) GetChangeId() string {
	if m != nil && m.ChangeId != nil {
		return *m.ChangeId
	}
	return ""
}

func (m *Change) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Change) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Change) GetAuthMechanism() string {
	if m != nil && m.AuthMechanism != nil {
		return *m.AuthMechanism
	}
	return ""
}

func (m *Change) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *Change) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Change) GetConfig() string {
	if m != nil && m.Config != nil {
		return *m.Config
	}
	return ""
}

func (m *Change) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Change) GetOldConfig() string {
	if m != nil && m.OldConfig != nil {
		return *m.OldConfig
	}
	return ""
}

func init() {
}
