// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/config-service/proto/compile/compile.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_config_compile is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/config-service/proto/compile/compile.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_config_compile

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Id               []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type Response struct {
	Config           *string `protobuf:"bytes,1,req,name=config" json:"config,omitempty"`
	Hash             *string `protobuf:"bytes,2,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetConfig() string {
	if m != nil && m.Config != nil {
		return *m.Config
	}
	return ""
}

func (m *Response) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func init() {
}
