// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/config-service/proto/multicompile/multicompile.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_config_milticompile is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/config-service/proto/multicompile/multicompile.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_config_milticompile

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	CompileRequests  []*Request_CompileRequest `protobuf:"bytes,1,rep,name=compileRequests" json:"compileRequests,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetCompileRequests() []*Request_CompileRequest {
	if m != nil {
		return m.CompileRequests
	}
	return nil
}

type Request_CompileRequest struct {
	Id               []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	PreviousHash     *string  `protobuf:"bytes,3,opt,name=previousHash" json:"previousHash,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Request_CompileRequest) Reset()         { *m = Request_CompileRequest{} }
func (m *Request_CompileRequest) String() string { return proto.CompactTextString(m) }
func (*Request_CompileRequest) ProtoMessage()    {}

func (m *Request_CompileRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Request_CompileRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Request_CompileRequest) GetPreviousHash() string {
	if m != nil && m.PreviousHash != nil {
		return *m.PreviousHash
	}
	return ""
}

type Response struct {
	CompileResponses []*Response_CompileResponse `protobuf:"bytes,1,rep,name=compileResponses" json:"compileResponses,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetCompileResponses() []*Response_CompileResponse {
	if m != nil {
		return m.CompileResponses
	}
	return nil
}

type Response_CompileResponse struct {
	Config           *string `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	Hash             *string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Error            *bool   `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response_CompileResponse) Reset()         { *m = Response_CompileResponse{} }
func (m *Response_CompileResponse) String() string { return proto.CompactTextString(m) }
func (*Response_CompileResponse) ProtoMessage()    {}

func (m *Response_CompileResponse) GetConfig() string {
	if m != nil && m.Config != nil {
		return *m.Config
	}
	return ""
}

func (m *Response_CompileResponse) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *Response_CompileResponse) GetError() bool {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return false
}

func init() {
}
